port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - {name: 1 导航页：bit.ly/3NLNLoJ, server: 8.8.8.8, port: 8000, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇭🇰 香港 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇭🇰 香港 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇭🇰 香港 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇭🇰 香港 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇭🇰 香港 05, server: cname01d-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇭🇰 香港 06 [0.8x]", server: v1abc123.sched.sma-dk.hfifx.xin, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇭🇰 香港 07 [0.8x]", server: static-abcde12345.cdn.hfifx.xin, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇭🇰 香港 08 [0.8x]", server: static-1q2w3e4r5t.cdn.hfifx.xin, port: 8011, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇯🇵 日本 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇯🇵 日本 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇯🇵 日本 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇯🇵 日本 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇯🇵 日本 05, server: cname01d-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇯🇵 日本 06 [0.8x]", server: v1abc123.sched.sma-dk.hfifx.xin, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇯🇵 日本 07 [0.8x]", server: static-abcde12345.cdn.hfifx.xin, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇯🇵 日本 08 [0.8x]", server: static-1q2w3e4r5t.cdn.hfifx.xin, port: 8021, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇺🇸 美国 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇺🇸 美国 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇺🇸 美国 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇺🇸 美国 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇺🇸 美国 05, server: cname01d-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇺🇸 美国 06 [0.8x]", server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇺🇸 美国 07 [0.8x]", server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8031, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇬 新加坡 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇬 新加坡 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇬 新加坡 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇬 新加坡 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇬 新加坡 05, server: cname01d-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇸🇬 新加坡 06 [0.8x]", server: v1abc123.sched.sma-dk.hfifx.xin, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇸🇬 新加坡 07 [0.8x]", server: static-abcde12345.cdn.hfifx.xin, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇸🇬 新加坡 08 [0.8x]", server: static-1q2w3e4r5t.cdn.hfifx.xin, port: 8041, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇳 台湾 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇳 台湾 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇳 台湾 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇳 台湾 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇳 台湾 05, server: cname01-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇳 台湾 06 [0.8x]", server: v1abc123.sched.sma-dk.hfifx.xin, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇳 台湾 07 [0.8x]", server: static-abcde12345.cdn.hfifx.xin, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇳 台湾 08 [0.8x]", server: static-1q2w3e4r5t.cdn.hfifx.xin, port: 8051, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇳 台湾 09 [原生]", server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8005, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇰🇷 韩国 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8061, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇰🇷 韩国 02, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8061, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇰🇷 韩国 03, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8061, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇦 加拿大 01, server: cname01-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇦 加拿大 02, server: cname01a-njidwp5y5gbd7lbd.pompei4257.xyz, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇦 加拿大 03, server: cname01b-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇦 加拿大 04, server: cname01c-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇦 加拿大 05, server: cname01d-njidwp5y5gbd7lbd.costiera5153.xyz, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇦 加拿大 06 [0.8x]", server: v1abc123.sched.sma-dk.hfifx.xin, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇦 加拿大 07 [0.8x]", server: static-abcde12345.cdn.hfifx.xin, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: "🇨🇦 加拿大 08 [0.8x]", server: static-1q2w3e4r5t.cdn.hfifx.xin, port: 8091, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇮🇱 冷门-以色列, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8071, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇷🇺 冷门-俄罗斯01, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8085, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇷🇺 冷门-俄罗斯02, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8086, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇿🇦 冷门-南非, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8072, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇮🇳 冷门-印度, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8073, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇹🇷 冷门-土耳其, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8087, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇲🇽 冷门-墨西哥, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8074, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇧🇷 冷门-巴西, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8075, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇩🇪 冷门-德国, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8076, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇨🇱 冷门-智利, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8077, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇫🇷 冷门-法国, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8078, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇵🇱 冷门-波兰, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8079, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇦🇺 冷门-澳大利亚, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8070, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇸🇪 冷门-瑞典, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8081, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇬🇧 冷门-英国, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8082, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇪🇸 冷门-西班牙, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8083, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇳🇱 冷门-阿姆斯特丹, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8084, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
  - {name: 🇦🇷 冷门-阿根廷, server: cnamelm-dwzksl7kzye3rdby.ravenna0943.xyz, port: 8089, type: ssr, cipher: aes-256-cfb, password: LjtFzy, protocol: auth_aes128_md5, obfs: http_simple, protocol-param: 61319:KLiG41U7vLYdwB5f, obfs-param: 5d49361319.microsoft.com, udp: true}
proxy-groups:
  - name: 🚀 手动选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 💬 即时通讯
    type: select
    proxies:
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
  - name: 🌐 社交媒体
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🚀 GitHub
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
  - name: 🤖 ChatGPT
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🤖 Copilot
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🤖 AI服务
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎶 TikTok
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 📹 YouTube
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 Netflix
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 DisneyPlus
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 HBO
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 PrimeVideo
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 AppleTV+
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎥 Emby
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🎻 Spotify
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 📺 Bahamut
    type: select
    proxies:
      - 🇼🇸 台湾节点
      - 🚀 手动选择
      - 🎯 全球直连
  - name: 🌎 国外媒体
    type: select
    proxies:
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🛒 国外电商
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
  - name: 🇬 谷歌服务
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
  - name: 🎮 游戏平台
    type: select
    proxies:
      - 🎯 全球直连
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
  - name: 🎮 Steam
    type: select
    proxies:
      - 🎯 全球直连
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🚀 测速工具
    type: select
    proxies:
      - 🎯 全球直连
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点
      - 🇼🇸 台湾节点
      - 🇰🇷 韩国节点
      - 🇨🇦 加拿大节点
      - 🇬🇧 英国节点
      - 🇫🇷 法国节点
      - 🇩🇪 德国节点
      - 🇳🇱 荷兰节点
      - 🇹🇷 土耳其节点
      - 🌐 其他地区
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇹🇷 冷门-土耳其
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇩🇪 冷门-德国
      - 🇨🇱 冷门-智利
      - 🇫🇷 冷门-法国
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇬🇧 冷门-英国
      - 🇪🇸 冷门-西班牙
      - 🇳🇱 冷门-阿姆斯特丹
      - 🇦🇷 冷门-阿根廷
  - name: 🔀 非标端口
    type: select
    proxies:
      - 🐟 遵循规则
      - 🎯 全球直连
  - name: 🇭🇰 香港节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇭🇰 香港 01
      - 🇭🇰 香港 02
      - 🇭🇰 香港 03
      - 🇭🇰 香港 04
      - 🇭🇰 香港 05
      - 🇭🇰 香港 06 [0.8x]
      - 🇭🇰 香港 07 [0.8x]
      - 🇭🇰 香港 08 [0.8x]
  - name: 🇺🇸 美国节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇺🇸 美国 01
      - 🇺🇸 美国 02
      - 🇺🇸 美国 03
      - 🇺🇸 美国 04
      - 🇺🇸 美国 05
      - 🇺🇸 美国 06 [0.8x]
      - 🇺🇸 美国 07 [0.8x]
  - name: 🇯🇵 日本节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇯🇵 日本 01
      - 🇯🇵 日本 02
      - 🇯🇵 日本 03
      - 🇯🇵 日本 04
      - 🇯🇵 日本 05
      - 🇯🇵 日本 06 [0.8x]
      - 🇯🇵 日本 07 [0.8x]
      - 🇯🇵 日本 08 [0.8x]
  - name: 🇸🇬 新加坡节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇸🇬 新加坡 01
      - 🇸🇬 新加坡 02
      - 🇸🇬 新加坡 03
      - 🇸🇬 新加坡 04
      - 🇸🇬 新加坡 05
      - 🇸🇬 新加坡 06 [0.8x]
      - 🇸🇬 新加坡 07 [0.8x]
      - 🇸🇬 新加坡 08 [0.8x]
  - name: 🇼🇸 台湾节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇨🇳 台湾 01
      - 🇨🇳 台湾 02
      - 🇨🇳 台湾 03
      - 🇨🇳 台湾 04
      - 🇨🇳 台湾 05
      - 🇨🇳 台湾 06 [0.8x]
      - 🇨🇳 台湾 07 [0.8x]
      - 🇨🇳 台湾 08 [0.8x]
      - 🇨🇳 台湾 09 [原生]
  - name: 🇰🇷 韩国节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇰🇷 韩国 01
      - 🇰🇷 韩国 02
      - 🇰🇷 韩国 03
  - name: 🇨🇦 加拿大节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇨🇦 加拿大 01
      - 🇨🇦 加拿大 02
      - 🇨🇦 加拿大 03
      - 🇨🇦 加拿大 04
      - 🇨🇦 加拿大 05
      - 🇨🇦 加拿大 06 [0.8x]
      - 🇨🇦 加拿大 07 [0.8x]
      - 🇨🇦 加拿大 08 [0.8x]
  - name: 🇬🇧 英国节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇬🇧 冷门-英国
  - name: 🇫🇷 法国节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇫🇷 冷门-法国
  - name: 🇩🇪 德国节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇩🇪 冷门-德国
  - name: 🇳🇱 荷兰节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇳🇱 冷门-阿姆斯特丹
  - name: 🇹🇷 土耳其节点
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇹🇷 冷门-土耳其
  - name: 🌐 其他地区
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 1 导航页：bit.ly/3NLNLoJ
      - 🇮🇱 冷门-以色列
      - 🇷🇺 冷门-俄罗斯01
      - 🇷🇺 冷门-俄罗斯02
      - 🇿🇦 冷门-南非
      - 🇮🇳 冷门-印度
      - 🇲🇽 冷门-墨西哥
      - 🇧🇷 冷门-巴西
      - 🇨🇱 冷门-智利
      - 🇵🇱 冷门-波兰
      - 🇦🇺 冷门-澳大利亚
      - 🇸🇪 冷门-瑞典
      - 🇪🇸 冷门-西班牙
      - 🇦🇷 冷门-阿根廷
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 遵循规则
    type: select
    proxies:
      - 🐟 漏网之鱼
rules:
  - GEOSITE,private,🎯 全球直连
  - GEOIP,private,🎯 全球直连,no-resolve
  - RULE-SET,Custom_Direct_Classical,🎯 全球直连
  - RULE-SET,Custom_Proxy_Classical,🚀 手动选择
  - GEOSITE,google-cn,🎯 全球直连
  - GEOSITE,category-games@cn,🎯 全球直连
  - RULE-SET,Steam_CDN_Classical,🎯 全球直连
  - GEOSITE,category-game-platforms-download,🎯 全球直连
  - GEOSITE,category-public-tracker,🎯 全球直连
  - GEOSITE,category-communication,💬 即时通讯
  - GEOSITE,category-social-media-!cn,🌐 社交媒体
  - GEOSITE,openai,🤖 ChatGPT
  - GEOSITE,bing,🤖 Copilot
  - GEOSITE,category-ai-!cn,🤖 AI服务
  - GEOSITE,github,🚀 GitHub
  - GEOSITE,category-speedtest,🚀 测速工具
  - GEOSITE,steam,🎮 Steam
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,apple-tvplus,🎥 AppleTV+
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,microsoft,Ⓜ️ 微软服务
  - GEOSITE,googlefcm,📢 谷歌FCM
  - GEOSITE,google,🇬 谷歌服务
  - GEOSITE,tiktok,🎶 TikTok
  - GEOSITE,netflix,🎥 Netflix
  - GEOSITE,disney,🎥 DisneyPlus
  - GEOSITE,hbo,🎥 HBO
  - GEOSITE,primevideo,🎥 PrimeVideo
  - GEOSITE,category-emby,🎥 Emby
  - GEOSITE,spotify,🎻 Spotify
  - GEOSITE,bahamut,📺 Bahamut
  - GEOSITE,category-games,🎮 游戏平台
  - GEOSITE,category-entertainment,🌎 国外媒体
  - GEOSITE,category-ecommerce,🛒 国外电商
  - GEOSITE,gfw,🚀 手动选择
  - GEOIP,telegram,💬 即时通讯,no-resolve
  - GEOIP,twitter,🌐 社交媒体,no-resolve
  - GEOIP,facebook,🌐 社交媒体,no-resolve
  - GEOIP,google,🇬 谷歌服务,no-resolve
  - GEOIP,netflix,🎥 Netflix,no-resolve
  - GEOSITE,cn,🎯 全球直连
  - GEOIP,cn,🎯 全球直连,no-resolve
  - RULE-SET,Custom_Port_Direct,🔀 非标端口
  - MATCH,🐟 漏网之鱼
rule-providers:
  Custom_Direct_Classical:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical.yaml
    path: ./providers/15519759398106057482.yaml
    interval: 28800
  Custom_Proxy_Classical:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical.yaml
    path: ./providers/5958306251279867197.yaml
    interval: 28800
  Steam_CDN_Classical:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml
    path: ./providers/13268481674871578153.yaml
    interval: 28800
  Custom_Port_Direct:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml
    path: ./providers/2451647452112462632.yaml
    interval: 28800